# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://hashan-peiris.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: "Hashan C. Peiris"
# Description of the Site
description: "Advanced research and industrial experience in computational materials science, catalysis, battery interfaces, failure analysis, and manufacturing. Proven ability to drive interdisciplinary projects across academia and industry."
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: "Materials Science, DFT, AIMD, Machine Learning, Batteries, Catalysis, Failure Analysis, HPC, Research, Industry, Binghamton University, VASP, Quantum Espresso, USPEX, Python, Leadership"
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
#heroimage: https://www.bing.com/images/create/a-professional-but-creative-and-inspirational-imag/64d023bea65f413b9acfbbd69d1452a0?id=iBhRB38gHg2Y99plXgQTGQ%3d%3d&view=detailv2&idpp=genimg&idpclose=1&FORM=SYDBIC

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: peiris.mdhc@gmail.com
#facebook_username: Hashan Peiris
#twitter_username: \@HashanPeiris6
#instagram_username: thedevslot
linkedin_username: m-d-hashan-c-peiris-aa9b65146
github_username:  Hashan-Peiris
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Hashan C. Peiris
# URL for the Image of the Author
author-image: /assets/images/Hashan-Peiris.jpg
# 60 Words About the Author
author-about: >
  Computational materials scientist and engineer delivering impactful solutions to challenges at the edge of research and industry. Skilled in advanced modeling (DFT, AIMD, ML), hands-on manufacturing plant operations, system inspection, quality/failure analysis, and interdisciplinary project leadership. Recognized for mentorship, grant writing, and effective project management across high-performing teams.
author-url: https://www.linkedin.com/in/m-d-hashan-c-peiris-aa9b65146/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-feed

# Permalink
permalink: "blog/:title"


# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: "Advanced research and industrial experience in computational materials science, catalysis, battery interfaces, failure analysis, and manufacturing. Proven ability to drive interdisciplinary projects across academia and industry."
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
